// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentTask = { id: string, workspace_id: string, card_id: string, state: string, attempt: number, max_attempts: number, branch: string | null, worktree_path: string | null, window_id: string | null, events_file: string | null, fail_reason: string | null, last_event_at: string | null, started_at: string | null, finished_at: string | null, created_at: string, updated_at: string, };
