// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentEvent = { id: number, workspace_id: string, task_id: string | null, job_id: string | null, ts: string, kind: string, level: string, payload_json: string | null, cost_usd: number | null, num_turns: number | null, duration_ms: number | null, };
