// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardColumn } from "./BoardColumn";
import type { Card } from "./Card";

export type BoardGetResult = { columns: Array<BoardColumn>, cards: Array<Card>, };
