// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Card = { id: string, workspace_id: string, column_id: string, title: string, body_preview: string | null, position: number, source: string, github_issue_number: number | null, github_state: string | null, assignee: string | null, labels_json: string | null, remote_updated_at: string | null, terminal_window_id: string | null, created_at: string, updated_at: string, };
