// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { IssueComment } from "./IssueComment";
import type { Label } from "./Label";

export type CardDetail = { card: Card, body: string | null, comments: Array<IssueComment>, labels: Array<Label>, assignee_avatar_url: string | null, };
