// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IssueProposal = { id: string, job_id: string, workspace_id: string, ord: number, title: string, body: string, labels_json: string | null, depends_on_json: string | null, acceptance_json: string | null, priority: string | null, status: string, card_id: string | null, };
