// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IssueComment = { id: number, user_login: string, user_avatar_url: string | null, body: string, created_at: string, updated_at: string, };
