// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A GitHub label with its display colour. Used by the card detail view to
 * render coloured chips; the board/ledger only needs names (see
 * `RemoteIssue.labels`).
 */
export type Label = { name: string, color: string, };
