// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Workspace = { id: string, name: string, slug: string, root_path: string, github_owner: string | null, github_repo: string | null, startup_command: string | null, created_at: string, };
